/**
 * @file utils/encryption.js
 * @module utils/encryption
 * @description Application-Layer Field Encryption at Rest (NFR-22).
 *
 * Implements authenticated encryption for sensitive database fields (email addresses,
 * IP address logs, session metadata) using AES-256-GCM before writing to MongoDB.
 *
 * CRYPTOGRAPHIC SPECIFICATION:
 * - Cipher: AES-256-GCM (Galois/Counter Mode, authenticated AEAD cipher).
 * - Key Length: 256 bits (32 bytes), loaded strictly from the `FIELD_ENCRYPTION_KEY`
 *   environment variable. Never hardcoded or stored in the database.
 * - Initialization Vector (IV): 96 bits (12 bytes) of cryptographically random entropy
 *   generated fresh for every encryption operation (`crypto.randomBytes(12)`).
 * - Authentication Tag: 128 bits (16 bytes) generated by GCM to guarantee ciphertext
 *   authenticity and detect any at-rest bit tampering.
 * - Blind Index: Deterministic HMAC-SHA256 hash derived via HKDF (RFC 5869) to permit
 *   fast, O(1) indexed equality lookups (e.g. `User.findOne({ email })`) without exposing
 *   plaintext or using deterministic cipher mode.
 * - Serialized Storage Format:
 *     enc:gcm:<iv_24_hex>:<tag_32_hex>:<ciphertext_hex>
 */

const crypto = require('crypto');

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH_BYTES = 12; // 96 bits per NIST SP 800-38D recommendations
const AUTH_TAG_LENGTH_BYTES = 16; // 128 bits
const ENCRYPTION_PREFIX = 'enc:gcm:';
const REGEX_CIPHERTEXT = /^enc:gcm:([0-9a-f]{24}):([0-9a-f]{32}):([0-9a-f]+)$/i;

// In-memory cache for derived sub-keys (HKDF)
let cachedMasterKey = null;
let cachedCipherKey = null;
let cachedIndexKey = null;

/**
 * Resolves the 32-byte master key from environment variables.
 *
 * @throws {Error} If FIELD_ENCRYPTION_KEY is missing or invalid
 * @returns {Buffer} 32-byte key buffer
 */
function getMasterKey() {
  const envKey = process.env.FIELD_ENCRYPTION_KEY;

  if (!envKey) {
    if (process.env.NODE_ENV === 'production') {
      throw new Error('[FATAL] FIELD_ENCRYPTION_KEY environment variable is required for NFR-22.');
    }
    // Safe deterministic development fallback to avoid crashing unconfigured dev runs
    return crypto.createHash('sha256').update('collabide-default-dev-field-encryption-key-2026').digest();
  }

  // Support 64 hex characters (32 bytes) or 32 raw ASCII characters
  if (/^[0-9a-fA-F]{64}$/.test(envKey)) {
    return Buffer.from(envKey, 'hex');
  }

  const buf = Buffer.from(envKey, 'utf8');
  if (buf.length === 32) {
    return buf;
  }

  // Hash key if non-standard length to guarantee exact 256 bits
  return crypto.createHash('sha256').update(buf).digest();
}

/**
 * Derives operational keys (cipher key + blind index HMAC key) using HKDF (RFC 5869).
 *
 * @returns {{ cipherKey: Buffer, indexKey: Buffer }} Derived cryptographic keys
 */
function getKeys() {
  const masterKey = getMasterKey();

  if (cachedMasterKey && cachedMasterKey.equals(masterKey)) {
    return { cipherKey: cachedCipherKey, indexKey: cachedIndexKey };
  }

  // HKDF key derivation guarantees cryptographically independent keys
  const cipherKey = crypto.hkdfSync('sha256', masterKey, '', 'collabide-aes-256-gcm-cipher', 32);
  const indexKey = crypto.hkdfSync('sha256', masterKey, '', 'collabide-blind-index-hmac', 32);

  cachedMasterKey = masterKey;
  cachedCipherKey = Buffer.from(cipherKey);
  cachedIndexKey = Buffer.from(indexKey);

  return { cipherKey: cachedCipherKey, indexKey: cachedIndexKey };
}

/**
 * Checks whether a given string is an AES-256-GCM encrypted payload.
 *
 * @param {*} val - Value to check
 * @returns {boolean} True if string matches encrypted format
 */
function isEncrypted(val) {
  if (typeof val !== 'string') return false;
  return REGEX_CIPHERTEXT.test(val);
}

/**
 * Encrypts a plain text string using AES-256-GCM with a random IV (NFR-22).
 *
 * @param {string|null|undefined} plaintext - Plain text content to encrypt
 * @returns {string|null|undefined} Encrypted string in `enc:gcm:<iv>:<tag>:<ciphertext>` format
 */
function encrypt(plaintext) {
  if (plaintext === null || plaintext === undefined) return plaintext;
  if (typeof plaintext !== 'string') plaintext = String(plaintext);
  if (plaintext.trim().length === 0) return plaintext;

  // Idempotency: Do not re-encrypt already encrypted payloads
  if (isEncrypted(plaintext)) return plaintext;

  const { cipherKey } = getKeys();
  const iv = crypto.randomBytes(IV_LENGTH_BYTES);
  const cipher = crypto.createCipheriv(ALGORITHM, cipherKey, iv, {
    authTagLength: AUTH_TAG_LENGTH_BYTES,
  });

  let encrypted = cipher.update(plaintext, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  const tag = cipher.getAuthTag();

  return `${ENCRYPTION_PREFIX}${iv.toString('hex')}:${tag.toString('hex')}:${encrypted}`;
}

/**
 * Decrypts an AES-256-GCM encrypted string, validating authenticity tag (NFR-22).
 *
 * @param {string|null|undefined} ciphertextStr - Serialized ciphertext string
 * @returns {string|null|undefined} Decrypted plain text UTF-8 string
 * @throws {Error} If authentication tag fails (data corruption or bit tampering)
 */
function decrypt(ciphertextStr) {
  if (ciphertextStr === null || ciphertextStr === undefined) return ciphertextStr;
  if (typeof ciphertextStr !== 'string') return ciphertextStr;

  const match = ciphertextStr.match(REGEX_CIPHERTEXT);
  if (!match) {
    // Graceful backward-compatibility: Return plaintext if not encrypted
    return ciphertextStr;
  }

  const [, ivHex, tagHex, dataHex] = match;
  const { cipherKey } = getKeys();

  const iv = Buffer.from(ivHex, 'hex');
  const tag = Buffer.from(tagHex, 'hex');
  const decipher = crypto.createDecipheriv(ALGORITHM, cipherKey, iv, {
    authTagLength: AUTH_TAG_LENGTH_BYTES,
  });

  decipher.setAuthTag(tag);

  let decrypted = decipher.update(dataHex, 'hex', 'utf8');
  decrypted += decipher.final('utf8');

  return decrypted;
}

/**
 * Computes a deterministic HMAC-SHA256 blind index hash for searchable encrypted fields.
 * Enables exact-match database queries (`User.findOne({ email })`) without exposing plaintext.
 *
 * @param {string|null|undefined} value - String value to hash (e.g. email or IP)
 * @returns {string|null|undefined} 64-character lowercase hex digest
 */
function hashBlindIndex(value) {
  if (value === null || value === undefined) return value;
  const normalized = String(value).toLowerCase().trim();
  if (normalized.length === 0) return '';

  const { indexKey } = getKeys();
  return crypto.createHmac('sha256', indexKey).update(normalized).digest('hex');
}

module.exports = {
  encrypt,
  decrypt,
  isEncrypted,
  hashBlindIndex,
  blindIndex: hashBlindIndex,
  ALGORITHM,
  ENCRYPTION_PREFIX,
};
